package com.azrinurvani.newsapicompose.presentation.component.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF005342)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF087B63)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF44655A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCAEFE0)
val onSecondaryContainerLight = Color(0xFF305146)
val tertiaryLight = Color(0xFF4C3F80)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF7163A7)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF6FAF7)
val onBackgroundLight = Color(0xFF181D1B)
val surfaceLight = Color(0xFFF6FAF7)
val onSurfaceLight = Color(0xFF181D1B)
val surfaceVariantLight = Color(0xFFD9E5DF)
val onSurfaceVariantLight = Color(0xFF3E4945)
val outlineLight = Color(0xFF6E7A74)
val outlineVariantLight = Color(0xFFBDC9C3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D312F)
val inverseOnSurfaceLight = Color(0xFFEDF2EE)
val inversePrimaryLight = Color(0xFF7BD8BB)
val surfaceDimLight = Color(0xFFD7DBD7)
val surfaceBrightLight = Color(0xFFF6FAF7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F5F1)
val surfaceContainerLight = Color(0xFFEBEFEB)
val surfaceContainerHighLight = Color(0xFFE5E9E5)
val surfaceContainerHighestLight = Color(0xFFDFE4E0)

val primaryDark = Color(0xFF7BD8BB)
val onPrimaryDark = Color(0xFF00382B)
val primaryContainerDark = Color(0xFF00705A)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFAACEC0)
val onSecondaryDark = Color(0xFF15362D)
val secondaryContainerDark = Color(0xFF24453B)
val onSecondaryContainerDark = Color(0xFFB7DCCD)
val tertiaryDark = Color(0xFFCCBEFF)
val onTertiaryDark = Color(0xFF332565)
val tertiaryContainerDark = Color(0xFF67599C)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101412)
val onBackgroundDark = Color(0xFFDFE4E0)
val surfaceDark = Color(0xFF101412)
val onSurfaceDark = Color(0xFFDFE4E0)
val surfaceVariantDark = Color(0xFF3E4945)
val onSurfaceVariantDark = Color(0xFFBDC9C3)
val outlineDark = Color(0xFF88938E)
val outlineVariantDark = Color(0xFF3E4945)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDFE4E0)
val inverseOnSurfaceDark = Color(0xFF2D312F)
val inversePrimaryDark = Color(0xFF006B56)
val surfaceDimDark = Color(0xFF101412)
val surfaceBrightDark = Color(0xFF353A38)
val surfaceContainerLowestDark = Color(0xFF0A0F0D)
val surfaceContainerLowDark = Color(0xFF181D1B)
val surfaceContainerDark = Color(0xFF1C211F)
val surfaceContainerHighDark = Color(0xFF262B29)
val surfaceContainerHighestDark = Color(0xFF313634)







